### PR TITLE
chore: bump minimum Python version to 3.10

### PR DESCRIPTION
**Pull request by lengau**
Since charmcraft is on core22 now, we can drop the Python 3.8 requirements.

I'd recommend we rebase & merge this without squashing since bumping to Python 3.10 got ruff very excited (second commit).

### CODE REVIEW

**Review by sergiusens — APPROVED** [review]

**Review by syu-w — APPROVED** [review]

**Comment by lengau** [comment]
@sergiusens could you adjust the required tests for main branch merge?

* run-tests: replace ubuntu-20.04, 3.8 with ubuntu-22.04, 3.10
* run-tests: replace windows-2019, 3.8 with windows-2022, 3.10

**Comment by lengau** [comment]
[Waiting on merge until after the 2.5 branch]

**Comment by lengau** [comment]
Store test failure is marked in: https://github.com/canonical/charmcraft/issues/1362

**Comment by lengau** [comment]
@sergiusens please bypass protections and merge this. It still wants the tests that I've removed.

**Pull request merged**
