### PR TITLE
feat: fastapi-framework init profile and extension

### PR DESCRIPTION
**Pull request by javierdelapuente**
This PR implements the spec ISD160 - 12-Factor FastAPI Support" for charmcraft.

For that, a new init profile called "fastapi-framework" and a new fastapi extension, called "fastapi-framework" are needed. These additions are similar to the flask and django init profiles and extensions.

For the fastapi profile, the base 24.04 is used.

### CODE REVIEW

**Review by jdkandersson — APPROVED** [review]

**Review by lengau — APPROVED** [review]

**Review by mr-cal — APPROVED** [review]
Assuming the extension works, this looks good to me.

@lengau, do you typically write spread tests for extensions in charmcraft?

**Review by lengau — CHANGES_REQUESTED** [review]
Good catch @mr-cal!

@javierdelapuente could you modify [tests/spread/commands/init-flask-framework](https://github.com/canonical/charmcraft/blob/main/tests/spread/commands/init-flask-framework/task.yaml) to test this?

As a rough step-by-step:

1. Rename the directory to `init-extensions`
2. Create `flask` and `fastapi` variants, setting the `PROFILE` environment variable to the relevant profile
3. Change the `charmcraft init` command to use `--profile ${PROFILE}`

**Comment by javierdelapuente** [comment]
> Good catch @mr-cal!
> 
> @javierdelapuente could you modify [tests/spread/commands/init-flask-framework](https://github.com/canonical/charmcraft/blob/main/tests/spread/commands/init-flask-framework/task.yaml) to test this?
> 
> As a rough step-by-step:
> 
> 1. Rename the directory to `init-extensions`
> 2. Create `flask` and `fastapi` variants, setting the `PROFILE` environment variable to the relevant profile
> 3. Change the `charmcraft init` command to use `--profile ${PROFILE}`

@lengau!, I have done it that way for all the missing frameworks (also go).

**Review by lengau — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
