### PR TITLE
Add coverage to unit tests by default in 'charmcraft init'

### PR DESCRIPTION
**Pull request by mthaddon**
I think it'd be nice to include a coverage report in the default unit test output from what's generated by 'charmcraft init'. This PR adds that.

### CODE REVIEW

**Comment by chipaca** [comment]
should we switch the template to use tox?

**Comment by mthaddon** [comment]
> should we switch the template to use tox?

I'd be happy to see that, as my team tends to favour tox for our charms. Worth doing as a separate PR, or would you like to see that here? And is that something you'd like me to have a go at or would you prefer to do it?

**Comment by chipaca** [comment]
I think it's something for a separate PR, at least, and we should first decide if it's the right thing.
The current approach works, and the resulting tests are faster to get up and running, but as we see more people use tox, I wonder if we should just bite the bullet across the board.
It's no longer my decision to make, though.

**Review by chipaca — APPROVED** [review]

**Review by facundobatista — APPROVED** [review]
Great, thanks!

**Review by cjp256 — APPROVED** [review]
LGTM

**Pull request merged**
