### PR TITLE
providers: account for project path in instance name (CRAFT-334)

### PR DESCRIPTION
**Pull request by cjp256**
If Charmcraft were to build the same project [name] simultaneously in
two different directories, collisions on the containers in use may
occur.

To account for this, this PR uses the project directory's inode in the
container name.  This will ensure uniqueness for projects in multiple
paths, but also seamlessly handle project directory moves that don't
cross the filesystem boundary, the common case.

Note that 'clean' command will not affect other project directories,
so the clean must occur in the original directory.  To handle any
potentially unassociated containers, future work will include more
sweeping purge capabilities for the clean command.  This is not unique
to the introduction of the use of the directory inode, but is
exacerbated by it.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

### CODE REVIEW

**Review by sergiusens — APPROVED** [review]
+1. I would prefer to have this as a built in to craft-providers. We should also look into adding a lock to avoid multiple runs in the same directory in a future PR.

**Comment by cjp256** [comment]
> +1. I would prefer to have this as a built in to craft-providers. We should also look into adding a lock to avoid multiple runs in the same directory in a future PR.

Yeah, it'd be useful to move some of this functionality over into craft-providers at this point.

**Review by facundobatista — COMMENTED** [review]
I wonder how multiplatform is to use the inode in the path. 

Maybe it's much easier to just add a random number to the path, to disambiguate it? e.g., the last 5 chars of `uuid.uuid4()`?

**Comment by sergiusens** [comment]
Path uuid should be a nice global solution indeed

**Comment by cjp256** [comment]
(1) I verified that Pathlib.stat().st_ino works on MacOS and Windows.  I suppose there may be filesystems it doesn't work on, but they'd likely be problematic for other reasons anyways.  I'll add that this implementation is scoped for LXD and Linux.

(2) I don't know what a "path uuid" is - just a UUID incorporating the path component in generation?

(3) Generating a completely random value or uuid would provide uniqueness, but would then require a way of mapping said project to random value. This would have to be done by dropping a config somewhere to provide the hints `project @ <path> = <this id>`.  Perfectly reasonable, but more work.  Instead of a file on the host, we could instead store this info in LXD's `user.user-data` configuration to track this.  Or add it to the `craft-image.conf` config, but that would require starting up containers/VMs to check it, so not great.

(4) We could encode the [optionally hashed] path into the name like we do for snapcraft's remote-build.  Con: Doesn't handle the common case of moving the project directory.

**Review by facundobatista — APPROVED** [review]
Thanks!

**Pull request merged**
