### PR TITLE
Merge 2.4.1 hotfixes

### PR DESCRIPTION
**Pull request by sergiusens**

### CODE REVIEW

**Review by syu-w — APPROVED** [review]

**Comment by sergiusens** [comment]
@lengau @syu-w only failure is the store test in #1209 

We should merge this before merging anything else to have a clean merge

**Comment by syu-w** [comment]
Put that fix in this PR?

**Comment by sergiusens** [comment]
@syu-w please revert those changes, it is not where this is supposed to happen

**Review by lengau — APPROVED** [review]

**Comment by sergiusens** [comment]
this is a merge back of what was actually released

**Comment by syu-w** [comment]
@sergiusens OK, reverted

**Review by lengau — APPROVED** [review]

**Pull request merged**
