### PR TITLE
ci: temporarily disable externally broken spread tests

### PR DESCRIPTION
**Pull request by lengau**
Related to #1193, this should make our CI succeed. We will need to re-enable these tests once the issues with those charms are resolved.

### CODE REVIEW

**Comment by sergiusens** [comment]
do we have an issue link for this one?

**Comment by lengau** [comment]
@sergiusens #1193

**Comment by jnsgruk** [comment]
@simskij any thoughts on the prometheus charm not building correctly? @lengau can you provide some example of where it's broken?

**Comment by lengau** [comment]
@jnsgruk These breakages are because of dependency issues related to a couple of third-party packages (jsonschema being one of them). Here's an example breakage: https://pipelines.actions.githubusercontent.com/serviceHosts/dd6d691f-d1ef-4869-a054-5c766a163a63/_apis/pipelines/1/runs/7391/signedlogcontent/11?urlExpires=2023-07-26T18%3A38%3A36.4349221Z&urlSigningMethod=HMACV1&urlSignature=7SeUO9O9yUGl2poXZMyfw52%2B6AO87TnO3jxhE5gSWJs%3D

I'm hoping to come up with a workaround/fix and fairly quickly release a version with that after I release 2.4.0 this week with Alma Linux support and such, and to include a restructure of our requirements handling in 3.0.

The relevant open issues are:

* #1178
* #1179 (a regression in my attempt to solve #1135 for a use case I wasn't aware of)

The root of the issue is an interaction with the current way we run pip to get dependencies, the `--no-binary` option and the fact that a lot of packages are starting to bring in rust dependencies. Unfortunately, there's no clear "good" solution.

**Review by syu-w — APPROVED** [review]

**Comment by sergiusens** [comment]
@lengau thanks, when I asked for the issue, I meant something to track to re-enable with later, seems you provided it in a different response

**Comment by lengau** [comment]
@sergiusens ope, sorry! In retrospect that makes more sense :-)

**Pull request merged**
