### PR TITLE
packaging, providers: update craft-parts to 1.0 (CRAFT-452)

### PR DESCRIPTION
**Pull request by cmatsuoka**
Update craft-parts version to 1.0 in package setup and requirements,
and remove unnecessary installation of sudo in provider setup.

### CODE REVIEW

**Comment by cjp256** [comment]
Can you add a set of integration / smoke tests which install build packages?

**Comment by cmatsuoka** [comment]
Added s smoke test using parts and build requires, both installing the package and not installing it if it's already present on the system (allowing charmcraft to run without superuser privileges in the latter case).

**Review by facundobatista — APPROVED** [review]
Nice!

**Review by cjp256 — APPROVED** [review]
Thanks!!

**Review by sergiusens — APPROVED** [review]

**Pull request merged**
