### PR TITLE
tests: improve multipass spread backend

### PR DESCRIPTION
**Pull request by lengau**
This allows multiple simultaneous workers with multipass using the same naming scheme the built-in lxd backend uses.

### CODE REVIEW

**Comment by mr-cal** [comment]
What do you think about making this a configurable feature?  8 multipass instances building charms simultaneously is too much for my laptop to handle

**Comment by lengau** [comment]
@mr-cal I'm happy to set the default number of workers to whatever. What about 2x 22.04 ones and 1x on the others?

**Comment by mr-cal** [comment]
Sounds like a good balance to me!

**Review by mr-cal — APPROVED** [review]

**Review by syu-w — APPROVED** [review]

**Comment by lengau** [comment]
@syu-w alas, spread (currently) only supports integer literals in this space. Might be worth a future feature request though.

**Pull request merged**
