### PR TITLE
templates: remove k8s info from machine charm template

### PR DESCRIPTION
**Pull request by lengau**
This change should make the `charm-upload-and-release` store task pass.

Progress on #1193

### CODE REVIEW

**Comment by lengau** [comment]
The broken store tests are part of #1193, but I'm fixing them independently.

**Comment by syu-w** [comment]
That part include its own tests, temporary remove it?

**Comment by lengau** [comment]
@syu-w — looking at what `charmcraft init` generated before we switched to only `charmcraft.yaml`, it probably shouldn't have that section anyway (we want `charmcraft init` to create as close as possible to a working charm, and machine charms don't use containers or resources). I also don't see any tests that are affected by this

**Comment by syu-w** [comment]
I think that part is to let people fill in some base info if they don't know how to use it. So maybe comment out them better than remove.

**Comment by lengau** [comment]
If someone wants to use those values they should use the `kubernetes` profile rather than the `machine` profile though?

**Comment by syu-w** [comment]
I am not sure, since it added as that.

**Comment by syu-w** [comment]
OK, I found that one is an error cause by symlink...
Old one do not have that.

https://github.com/canonical/template-operator/tree/charmcraft-templates/machine

**Review by syu-w — APPROVED** [review]

**Review by cmatsuoka — APPROVED** [review]

**Pull request merged**
