### PR TITLE
chore: merge main into feature/12f

### PR DESCRIPTION
**Pull request by gregory-schiano**
Merge main back into feature/12f to keep the branch up to date and ensure snapstore channel stays open

### CODE REVIEW

**Comment by gregory-schiano** [comment]
@lengau @syu-w I created a new PR with a single merge commit

**Comment by gregory-schiano** [comment]
Sorry I missed the `apply_extensions` fix in the Merge Commit

**Comment by lengau** [comment]
I'm working through this (Github is not very browser-friendly with large pull requests). ITMT, can you investigate the extensions test on macos? https://github.com/canonical/charmcraft/actions/runs/8061591136/job/22037370414?pr=1547

It looks like one of these tests is causing the runner to time out.

**Comment by lengau** [comment]
Looks good so far - please check out the test timeouts on macos as those will be a blocker for merge back to main. However, I'm not going to block that for this merge :-)

**Review by lengau — APPROVED** [review]

**Comment by lengau** [comment]
@syu-w when reviewing this it's probably easier to get it locally. With the GitHub CLI you can check it out with `gh pr checkout 1547`. I ended up doing both that and the approval through the GH CLI because I couldn't get the `/files` page to not absolutely crush my browser. After that it's only actually two commits to review

**Review by syu-w — APPROVED** [review]

**Pull request merged**
