### PR TITLE
build: add README.md by default

### PR DESCRIPTION
**Pull request by heitorPB**
The README.md file is used by CharmHub to display the contents of the
charm's page. This file should then be included by default.

### CODE REVIEW

**Comment by heitorPB** [comment]
I did not run the tests locally, as I can't install the dependencies... Could someone double check the instructions on the `CONTRIBUTING.md`? Installing the dependencies fail for the package `python-apt` on my setup (Ubuntu server 20.04, python 3.8):
```bash
$ pip install -r requirements-dev.txt -e .
[ ... ]
Collecting pyxdg
  Using cached pyxdg-0.27-py2.py3-none-any.whl (49 kB)
Collecting python-apt
  Using cached python-apt-0.7.8.tar.bz2 (49 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/h/projects/charmcraft/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-twzm095g/python-apt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-twzm095g/python-apt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-twzm095g/python-apt/pip-egg-info
         cwd: /tmp/pip-install-twzm095g/python-apt/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-twzm095g/python-apt/setup.py", line 6, in <module>
        from DistUtilsExtra.command import *
    ModuleNotFoundError: No module named 'DistUtilsExtra'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I do have the packages `python3-disutils{,-extra}` installed...

**Review by facundobatista — APPROVED** [review]
I like this, thanks!

**Review by sergiusens — APPROVED** [review]

**Comment by heitorPB** [comment]
Do I need to do something else to get this merged?

**Comment by heitorPB** [comment]
Just signed the CLA :)

**Pull request merged**
