### PR TITLE
feat: use ops.main() type hints

### PR DESCRIPTION
**Pull request by dimaqq**
The `ops.main` entry point will be properly typed starting with the upcoming release, ops==2.17.0

This PR updates the templates so that new charms use the fixed type hints.

It is paired with #1883 where charmcraft analyse validates that ops.main is called.

We'll be relying on charm repo static type checker to validate that ops.main is called with correct arguments.

- [x] wait for ops 2.17.0 to be released
- [x] update ops version in the templates
- [x] update ops.main() call in the templates

https://warthogs.atlassian.net/browse/CHARMTECH-276
parent: https://warthogs.atlassian.net/browse/CHARMTECH-219

### CODE REVIEW

**Comment by dimaqq** [comment]
In draft, as the new ops version has not been released yet, that's slated to end of the month.
@lengau I'd appreciate an early review, esp. if I missed something major.

**Review by lengau — APPROVED** [review]
LGTM. Let me know once you've fixed for the 2.17 release please.

**Comment by dimaqq** [comment]
@lengau ops 2.17.0 has been released and I've updated the ops dep specs

**Comment by lengau** [comment]
Thanks @dimaqq ! Looks good from my end. I'm merging another PR that adjusts the paas-app-charmer requirements (it's on the merge queue so it should merge in about an hour) - when that happens I'm guessing you'll have merge conflicts in those requirements templates, but they should be pretty obvious. Just a heads up so you're not surprised.

I've requested our mandatory second review from my team in case I've missed anything, so presumably we can merge this today.

**Review by mr-cal — APPROVED** [review]

**Pull request merged**
