### PR TITLE
fix: support `type:secret` in config.options

### PR DESCRIPTION
**Pull request by tonyandrewmeyer**
Since Juju 3.1, the `config.options` section of `charmcraft.yaml` (or the older `config.yaml`) has supported a `type` value of `secret` (for user secrets). This is missing from the documentation right now, but the Juju team are working on fixing that.

This PR adds support for `type: secret` in config options.

### CODE REVIEW

**Comment by tonyandrewmeyer** [comment]
cf. https://github.com/canonical/operator/issues/1166 where this was raised in ops.

**Comment by tonyandrewmeyer** [comment]
Argh, the CLA check failed because I carelessly did the merge in the GitHub UI and didn't associate it with my Canonical email address. Is there an easy way to fix that, like signing the CLA with my personal address also?

**Comment by benhoyt** [comment]
@tonyandrewmeyer Would you be able to rebase with the commit author set to your Canonical email to fix the CLA check? There also seem to be various CI failures (which I haven't looked at).

**Comment by tonyandrewmeyer** [comment]
Opened a replacement PR #1625.

**Pull request closed without merging**
