### PR TITLE
build: replace `black` with `ruff format` in charmcraft templates

### PR DESCRIPTION
**Pull request by jnsgruk**
As the title suggests! :)

Driveby to bump the default `ops` version to `2.8`

### CODE REVIEW

**Comment by tigarmo** [comment]
hey @jnsgruk is this (moving from black to ruff) a general guidance for our repos? If so, do we have any concerns wrt to Astral's possible monetization story moving forward?

**Comment by jnsgruk** [comment]
To be honest this is mostly because fewer deps = good imo. Astral may have a story, but this feels like core functionality.

**Review by lengau — APPROVED** [review]
We are astral of borg

**Review by mr-cal — APPROVED** [review]
:+1:

**Pull request merged**
