### PR TITLE
feat: validate devel bases with craft-application

### PR DESCRIPTION
**Pull request by mr-cal**
For https://github.com/canonical/craft-application/pull/302 and https://github.com/canonical/craft-application/issues/298

### CODE REVIEW

**Review by lengau — COMMENTED** [review]
This is a great demo of how apps would use the craft-application feature, thanks!

**Comment by mr-cal** [comment]
> This is a great demo of how apps would use the craft-application feature, thanks!

Free charmcraft development! 

Snapcraft, rockcraft, and charmcraft all define bases differently, I would have botched the craft-application code had I not tested it everywhere.

**Comment by mr-cal** [comment]
This PR will need to land after the next craft-application release.

I'm leaving this open and marked as a DRAFT to prevent accidental merges.

**Comment by mr-cal** [comment]
For now, this PR does not have to land due to changes in the craft-application.

That may change once https://github.com/canonical/craft-application/issues/348 is fixed.

**Pull request closed without merging**
